services:
  hw-mock:
    image: hw-mock:latest
    build:
      context: .
      dockerfile: DevOps/PiDev/Dockerfile
    privileged: true
    command: ["tail", "-f", "/dev/null"]
    environment:
      - DISPLAY=${DISPLAY}   # Forward the host's display
    stdin_open: true  # Keep stdin open for interaction
    tty: true         # Allocate a TTY for interactive Bash      
    volumes:
      - ./Test:/workspace/Test
    networks:
      - app-network
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket (optional)
    volumes:
      - mosquitto_config:/mosquitto/config  # Persist configuration
      - mosquitto_data:/mosquitto/data      # Persist data
      - mosquitto_log:/mosquitto/log        # Persist logs
    networks:
      - app-network

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_config:/etc/influxdb       # Persist configuration
      - influxdb_data:/var/lib/influxdb     # Persist data
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Grafana
    volumes:
      - grafana_config:/etc/grafana         # Persist configuration
      - grafana_data:/var/lib/grafana       # Persist data
    networks:
      - app-network
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:latest
    volumes:
    #  - telegraf_config:/etc/telegraf       # Persist configuration
      - ./DevOps/PiDev/Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - mqtt-broker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  raspberry_host_config:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  influxdb_config:
  influxdb_data:
  grafana_config:
  grafana_data:
  telegraf_config:
